### ISSUE TITLE
Drink reminder

### ISSUE THREAD

**Issue by JamieMcDonnell** [JessicaYeh/pebble-gallon-challenge#12]
Hi there, thanks for a great app! Not an issue but more a feature request - to help people hit their target, any chance of an hourly buzz reminder, and Bethan's a visual reminder to drink on the watch or phone? It would really help keep a drinking rhythm.
Thanks again ;)
Jamie

**Comment by JessicaYeh** [comment]
Hi Jamie! Great suggestion, I'll be sure to put this feature in the next version release of this app!

**Comment by JessicaYeh** [comment]
![image](https://cloud.githubusercontent.com/assets/3309218/6432225/85fb754e-c00f-11e4-8993-15f2d2e9c7bf.png)

Mockup of what this feature might look like. Feedback is welcome!

**Comment by JamieMcDonnell** [comment]
Exactly what I had in mind ;) looking forward to seeing it in the app and reaping the benefits ;)

Cheers!
Jamie

**Comment by JamieMcDonnell** [comment]
Just an idea, perhaps an Auto reminder mode that divides the number of portions (e.g. 8 pints) by the number of waking hours (8am > 9pm) and reminds regularly so water is drunk steadily during the day as apposed to for the first 8 hrs only - what do you think?

**Comment by JessicaYeh** [comment]
That sounds like a cool idea! So, to make sure I understand it correctly, instead of the user picking a time interval to be reminded at, it would automatically pick one for you, based on what all the other settings are? So for example, I set the app for a half gallon goal, and I drink in cup units. Assuming I sleep for 8 hours, I'm awake from 8am-midnight. That means I have 16 hours of awake time to drink. I have to drink 8 cups to meet my half gallon goal, so that means I have to drink a cup every 2 hours, so the auto reminder should remind me if I haven't drunken anything in 2 hours. Does this sort of sound like what you were thinking?

**Comment by JamieMcDonnell** [comment]
Hi Jessica,
yup that"s exactly what I was thinking, though I would give the option of
hourly reminders or these goal-orientated reminders - problem is drinking
before bed will have you up all night going to the toilet! So perhaps there
last reminder is issued an hour before "end of day"?

On 2 March 2015 at 07:42, Jessica Yeh notifications@github.com wrote:

> That sounds like a cool idea! So, to make sure I understand it correctly,
> instead of the user picking a time interval to be reminded at, it would
> automatically pick one for you, based on what all the other settings are?
> So for example, I set the app for a half gallon goal, and I drink in cup
> units. Assuming I sleep for 8 hours, I'm awake from 8am-midnight. That
> means I have 16 hours of awake time to drink. I have to drink 8 cups to
> meet my half gallon goal, so that means I have to drink a cup every 2
> hours, so the auto reminder should remind me if I haven't drunken anything
> in 2 hours. Does this sort of sound like what you were thinking?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JessicaYeh/pebble-gallon-challenge/issues/12#issuecomment-76665301
> .

## 

---

Jamie McDonnell | User Experience Design Evangelist and Developer |
 eFace2Face

mobile: (+420) 777 608 442 | email: jamie.mcdonnell@eface2face.com | web:
eface2face.com http://www.eface2face.com
[image: eface2face logo]  http://www.eface2face.com

[image: View our company profile on LinkedIn]
http://www.linkedin.com/company/eface2face

This electronic communication and any files transmitted with it, or
attached to it, are confidential and are intended solely for the use of the
individual or entity to who it is addressed and may contain information
that is confidential, legally privileged, protected by privacy laws, or
otherwise restricted from disclosure to anyone else. If you are not the
intended recipient or the person responsible for delivering the e-mail to
the intended recipient, be advised that you have received this e-mail in
error, and that any use, dissemination, forwarding, printing, or copying of
this e-mail is strictly prohibited. If you received this e-mail in error,
please return the e-mail to the sender, delete it from your computer and
destroy any printed copy of it. Although our company attempts to sweep
e-mail and attachments for viruses, it does not guarantee that either are
virus-free and accepts no liability for any damage sustained as a result of

## viruses.

**Comment by JessicaYeh** [comment]
Yup! There will be both options of hourly reminders and auto reminders. Instead of Off, 1 Hour, 2 Hours, etc, it will say Off, Auto, 1 Hour, 2 Hours, etc.

**Comment by JessicaYeh** [comment]
Good news, drink reminders are almost ready! The feature is finished, and the new app version will be posted to the app store at the end of this week (Friday). I'm going to continue testing it until then to make sure there are no remaining bugs.

Here are some screenshots of what it looks like, get excited!
![screenshot-settings2](https://cloud.githubusercontent.com/assets/3309218/6567397/c3ea73a6-c694-11e4-8c99-3ceb407adebb.png) ![screenshot-reminder-settings](https://cloud.githubusercontent.com/assets/3309218/6567399/cd3bdc42-c694-11e4-91fa-e26a59a4b0cc.png) ![screenshot-reminder](https://cloud.githubusercontent.com/assets/3309218/6567402/d26a0496-c694-11e4-8c23-732660d925f6.png)

**Comment by JamieMcDonnell** [comment]
Nice work - looking forward to the update ;) Without the reminders my water
consumption has been flagging!

Cheers

Jamie

On 10 March 2015 at 01:47, Jessica Yeh notifications@github.com wrote:

> Good news, drink reminders are almost ready! The feature is finished, and
> the new app version will be posted to the app store at the end of this week
> (Friday). I'm going to continue testing it until then to make sure there
> are no remaining bugs.
> 
> Here are some screenshots of what it looks like, get excited!
> [image: screenshot-settings2]
> https://cloud.githubusercontent.com/assets/3309218/6567397/c3ea73a6-c694-11e4-8c99-3ceb407adebb.png [image:
> screenshot-reminder-settings]
> https://cloud.githubusercontent.com/assets/3309218/6567399/cd3bdc42-c694-11e4-91fa-e26a59a4b0cc.png [image:
> screenshot-reminder]
> https://cloud.githubusercontent.com/assets/3309218/6567402/d26a0496-c694-11e4-8c23-732660d925f6.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JessicaYeh/pebble-gallon-challenge/issues/12#issuecomment-77975684
> .

## 

---

Jamie McDonnell | User Experience Design Evangelist and Developer |
 eFace2Face

mobile: (+420) 777 608 442 | email: jamie.mcdonnell@eface2face.com | web:
eface2face.com http://www.eface2face.com
[image: eface2face logo]  http://www.eface2face.com

[image: View our company profile on LinkedIn]
http://www.linkedin.com/company/eface2face

This electronic communication and any files transmitted with it, or
attached to it, are confidential and are intended solely for the use of the
individual or entity to who it is addressed and may contain information
that is confidential, legally privileged, protected by privacy laws, or
otherwise restricted from disclosure to anyone else. If you are not the
intended recipient or the person responsible for delivering the e-mail to
the intended recipient, be advised that you have received this e-mail in
error, and that any use, dissemination, forwarding, printing, or copying of
this e-mail is strictly prohibited. If you received this e-mail in error,
please return the e-mail to the sender, delete it from your computer and
destroy any printed copy of it. Although our company attempts to sweep
e-mail and attachments for viruses, it does not guarantee that either are
virus-free and accepts no liability for any damage sustained as a result of

## viruses.
