### ISSUE TITLE
Add a 'Begin of Day'. 

### ISSUE THREAD

**Issue by hilsonp** [JessicaYeh/pebble-gallon-challenge#18]
Because this weekend, your otherwise wonderful watchapp woke me up :-(

Thank you :-)

**Comment by JessicaYeh** [comment]
Great idea! I'll put this at the top of my to do list along with the metric unit mode for the next version of this app.

**Comment by hilsonp** [comment]
Thanks a lot.

**Comment by JessicaYeh** [comment]
Added in commit 8e35b048d411375720119ae39435fcc4108b729a, testing it now and will be added in the next version release! (next release should be soon, going to also finish metric unit mode).
