### ISSUE TITLE
Pebble menu icon

### ISSUE THREAD

**Issue by hilsonp** [JessicaYeh/pebble-gallon-challenge#19]
Hello Jessica,

You may give a little nice touch to your app by giving an icon to it in the Pebble menu like Gentle Wake or Misfit do. I think that the 2 drops you use in the Pebble App Store would display fine. Otherwise, Just use one drop. 

Just my 2 cents,

Pierre

**Comment by JessicaYeh** [comment]
Nice suggestion! I think it would look nice too, I'll also put it on my to do list for the next version.

**Comment by JessicaYeh** [comment]
Added in commit 7f4b708d6f42d0a14286492645a2a575b46d0802
![pebble-screenshot_2015-05-08_19-24-07](https://cloud.githubusercontent.com/assets/3309218/7547699/dd6fe7e6-f5b7-11e4-825d-2764b2f732dc.png)
