### ISSUE TITLE
Description hint

### ISSUE THREAD

**Issue by hilsonp** [JessicaYeh/pebble-gallon-challenge#20]
Hello again,

I post this here because I don't know how to contact you otherwise but this is definitely not a bug ;-)

This is just a funny fact you may use in your app description if you like. 

I was looking for an app (not a face) that would warn me for too long inactivity periods. By chance, I found your app that REALLY help me stay hydrated (thanks to the smart reminder). After a few days using it, I decided that I did not need the inactivity alarm because anyhow I need to stand up a walk a bit every now and then to refill my cup with water. 

So : Double THANK YOU !!!

**Comment by JessicaYeh** [comment]
Love your story! Glad you find the app useful!
