### ISSUE TITLE
Reminders not working

### ISSUE THREAD

**Issue by mattzuba** [JessicaYeh/pebble-gallon-challenge#21]
Maybe there have been changes in the Pebble SDK, but reminders aren't working for me.  I even attempted to recompile this with the 3.0 SDK and it still won't prompt them.  Does the App have to be open on the watch for reminders to work or should it work on a watchface as well?

I have a Pebble Time, but I couldn't make it work on either emulator on cloudpebble either.

**Comment by JessicaYeh** [comment]
Thanks for the report! I will definitely investigate this.

**Comment by mattzuba** [comment]
This may have been fixed by the latest firmware update - I've gotten two reminders today after updating the firmware yesterday.  However one of them came 45min before my 'start time'.  My start time is set to 7a, but I got a reminder at 6:15a

**Comment by JessicaYeh** [comment]
Is this issue still happening? I finally have some time now to look into it, but unfortunately I only have the original Pebble so I'm not sure how thoroughly I can test it :(

**Comment by JessicaYeh** [comment]
I finally got a Pebble Time, and looked into it, and there was indeed a change to the 3.0 SDK that messed up everything related to timing since they changed their C time functions to support time zones. It should be fixed now.

**Comment by mattzuba** [comment]
Awesome, thanks!

On Wed, Nov 11, 2015, 10:07 AM Jessica Yeh notifications@github.com wrote:

> I finally got a Pebble Time, and looked into it, and there was indeed a
> change to the 3.0 SDK that messed up everything related to timing since
> they changed their C time functions to support time zones. It should be
> fixed now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JessicaYeh/pebble-gallon-challenge/issues/21#issuecomment-155848454
> .
> 
> ## 

Thanks,
Matt Zuba
Sent from my mobile telecommunication device, please excuse any tpyos.
