### ISSUE TITLE
Pebble Time Round

### ISSUE THREAD

**Issue by akrabu** [JessicaYeh/pebble-gallon-challenge#22]
Any chance on a Round version?  :)

**Comment by JessicaYeh** [comment]
Absolutely! It might take me a while though, since I need to learn what the Round UI is like and how I could change my UI to be round since right now it's optimized for a rectangle.

**Comment by akrabu** [comment]
I'll be a guinea pig if you'd like!  You probably already know about this page, but it seems to be the place to start:  https://developer.getpebble.com/sdk/round-getting-started/

**Comment by JessicaYeh** [comment]
Haha awesome! Will definitely contact you once I start working on this, since I don't have a Pebble Round yet :( Pebble should provide developers with free access to all their devices ;)

**Comment by akrabu** [comment]
Haha yeah, I agree! And I'll be happy to help. I use your app daily.
Thanks! :)

**Comment by JessicaYeh** [comment]
Hi again! I just published a Pebble Round version to the app store. Wanna be my guinea pig and test it out? :) 

Oh, and I'm aware that the menu header labels are slightly cut off, I don't think there's currently anything I can do about that, though. :(

**Comment by akrabu** [comment]
Omg I get Pebble Health yesterday, and now Gallon Challenge today??  Well I
know what my two quick-launch apps are going to be again!  :D

Let's see...  when I first loaded it, my Pebble locked up for a bit.
Finally let me back out of it, and go back into it - then it worked fine.
It locked up for about two minutes.  Didn't crash, though.  Just wouldn't
respond to any button press.  It isn't doing that at all, now.  I'm
assuming it was building a database or something, perhaps?  Who knows.  The
Round is still a wee bit buggy, now and then.  Works fine for the most
part, though.  In addition, since I had left Gallon Challenge in my locker
so I could see if you ever updated it, it showed up on the app, but not my
watch.  Killed the app, reopened... same result.  Had to remove it
entirely, then add it back - that finally loaded it on my Pebble.

The UI looks normal.  Yeah, the headers are a little off.  I'm no Pebble
developer and don't know what's involved, but you might try centering them
just like the menu text?  That could be an easy fix - maybe make them
underlined to separate from the rest?  Either way, it works, and I'm happy
lol.

I'll be using it daily and I'll let you know if I find any bugs!  Thanks
for remembering me and letting me know you updated haha :)

Steven

**Comment by akrabu** [comment]
I'm not sure if you have a Round of your own or not - but in case you've
only seen what it looks like on the computer, here's a shot of it on my
wrist. :)

**Comment by JessicaYeh** [comment]
That's some interesting behavior with the installing. Unfortunately I don't have a physical Pebble Round so I can't try to reproduce that :( 

Thanks again for helping me test this! I'm happy that you and a lot of others use the app daily :)

**Comment by JessicaYeh** [comment]
Oh and I think GitHub may have eaten the picture you posted :( Can you post it again please?

**Comment by akrabu** [comment]
I'm happy to help!  Sorry, just now seeing these replies.  Google Inbox
decided to bundle these messages in my low priority bundle and I just now
found them haha.

Here's the pics!

https://ramlaw.mangoapps.com/sf/NzMyNjhfMTY4MTEyMw

https://ramlaw.mangoapps.com/sf/NzMyNjlfMTY4MTEyNA

Let me know if there's any more testing I can do!  It's been working like a
charm so far.

Steven
